### ISSUE TITLE
Update S3 URLs

### ISSUE THREAD

**Issue by cascadianblue** [Sage-Bionetworks/sandbox-provisioner#351]
New-style S3 urls should refer to buckets as a sub-domain.

E.g.:
https://s3-us-east-2.amazonaws.com/my-bucket-public/my_file.png
should instead be:
https://my-bucket-public.s3.amazonaws.com/my_file.png

See:
https://sagebionetworks.jira.com/browse/IT-790
and
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

**Comment by zaro0508** [comment]
mostly done.
