### ISSUE TITLE
add guidelines for issues and PRs

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/sandbox-provisioner#47]
Many times PRs are coming in without a clear description what they are for. Since the YAML format of CloudFormation templates does not always provide a description field, the PR description should indicate what it does.

We should institute GitHub ISSUE and PULL REQUEST templates to prompt submitters to provide the necessary information, and document their use in the README.

**Comment by zaro0508** [comment]
good idea but won't do
