### ISSUE TITLE
add docs about decommissioning a stack

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/sandbox-provisioner#49]
Document how to take down a stack, since @thomasyu888 tells me it isn't automated.

**Comment by thomasyu888** [comment]
Log into AWS, proceed to cloudFormation, Match stack name, delete stack after merge PR

**Comment by kdaily** [comment]
Add this to the README!

**Comment by zaro0508** [comment]
done, https://sagebionetworks.jira.com/wiki/spaces/IT/pages/756645932/Sage+AWS+Provisioner+Admin
